import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { ArtifactCard, ArtifactItem } from './ArtifactCard';
import { ArtifactPreview } from './ArtifactPreview';
import { FolderOpen, Filter, RefreshCw, Sparkles } from 'lucide-react';

const SAMPLE_ARTIFACTS: ArtifactItem[] = [
  {
    id: 's1-minutes',
    name: 'meeting_minutes.md',
    type: 'report',
    path: 'output/meeting_minutes.md',
    size: '2.4 KB',
    createdAt: 'Just now',
    locality: 'local',
    scenario: 'S1 Meeting Brief',
    content: `# Executive Meeting Minutes\n\n## Decisions\n- Adopt local-first model routing policy with zero data egress\n- Kokoro TTS selected for Apple Silicon speech synthesis\n\n## Action Items\n- [ ] Deploy MoFA gateway daemon to internal cluster (@devops)\n- [ ] Benchmark latency under 20 concurrent sessions (@ashum)\n\n## Risks\n- Cold start latency for 7B models requires preflight warmup`,
  },
  {
    id: 's1-brief',
    name: 'meeting_brief.mp3',
    type: 'audio',
    path: 'output/meeting_brief.mp3',
    size: '480 KB',
    createdAt: 'Just now',
    locality: 'local',
    scenario: 'S1 Meeting Brief',
  },
  {
    id: 's6-podcast',
    name: 'podcast_episode.mp3',
    type: 'audio',
    path: 'output/podcast_episode.mp3',
    size: '1.2 MB',
    createdAt: '5 min ago',
    locality: 'local',
    scenario: 'S6 Podcast Studio',
  },
  {
    id: 's4-explainer',
    name: 'explainer_video.mp4',
    type: 'video',
    path: 'output/explainer_video.mp4',
    size: '5.8 MB',
    createdAt: '12 min ago',
    locality: 'local',
    scenario: 'S4 Explainer Video',
  },
  {
    id: 's2-review',
    name: 'code_review_report.md',
    type: 'report',
    path: 'output/code_review_report.md',
    size: '3.1 KB',
    createdAt: '18 min ago',
    locality: 'local',
    scenario: 'S2 Code Review',
    content: `# PR Code Review Report\n\n## Security Findings\n- **BLOCKER**: Authentication token expiration disabled in \`auth/jwt.py\` line 14.\n- **RECOMMENDATION**: Reinstate expiration check before merging to main.\n\n## Thought Chain Trace\n- Model: Ollama deepseek-r1 / qwen2.5\n- Reasoning effort: HIGH (2,410 thought tokens)`,
  },
  {
    id: 's3-receipt',
    name: 'receipt_data.json',
    type: 'data',
    path: 'output/receipt_data.json',
    size: '0.9 KB',
    createdAt: '25 min ago',
    locality: 'local',
    scenario: 'S3 Document AI',
    content: `{\n  "merchant": "Apex Cloud Systems",\n  "date": "2026-08-20",\n  "items": [\n    {"name": "Developer Pro License", "qty": 1, "price": 49.00},\n    {"name": "Local Dedicated GPU Node", "qty": 1, "price": 120.00}\n  ],\n  "subtotal": 169.00,\n  "tax": 13.52,\n  "total": 182.52\n}`,
  },
];

export function ArtifactsGallery() {
  const [filter, setFilter] = useState<'all' | 'audio' | 'video' | 'report' | 'data'>('all');
  const [selectedArtifact, setSelectedArtifact] = useState<ArtifactItem | null>(null);

  const filteredArtifacts = SAMPLE_ARTIFACTS.filter(
    (item) => filter === 'all' || item.type === filter
  );

  return (
    <motion.div
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -8 }}
      className="flex-1 w-full flex flex-col p-8 overflow-y-auto"
    >
      {/* Gallery Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-8">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <FolderOpen className="w-5 h-5 text-accent-cyan" />
            <h2 className="text-xl font-bold text-text-primary">Artifacts Gallery</h2>
          </div>
          <p className="text-xs text-text-dim">
            Browse and preview media, reports, and structured data generated by MoFA pipelines.
          </p>
        </div>

        {/* Filter Pills */}
        <div className="flex items-center gap-1.5 p-1 bg-background-secondary/80 border border-border-subtle rounded-xl self-start sm:self-auto">
          {(['all', 'audio', 'video', 'report', 'data'] as const).map((type) => (
            <button
              key={type}
              onClick={() => setFilter(type)}
              className={`px-3 py-1 text-xs font-medium rounded-lg capitalize transition-colors ${
                filter === type
                  ? 'bg-white/10 text-text-primary shadow-sm'
                  : 'text-text-dim hover:text-text-secondary'
              }`}
            >
              {type}
            </button>
          ))}
        </div>
      </div>

      {/* Grid Layout */}
      {filteredArtifacts.length > 0 ? (
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
          {filteredArtifacts.map((artifact) => (
            <ArtifactCard
              key={artifact.id}
              artifact={artifact}
              onSelect={setSelectedArtifact}
            />
          ))}
        </div>
      ) : (
        <div className="flex flex-col items-center justify-center py-20 text-center">
          <FolderOpen className="w-12 h-12 text-text-dim/40 mb-3" />
          <p className="text-sm text-text-secondary font-medium">No artifacts found</p>
          <p className="text-xs text-text-dim mt-1">
            Run a scenario via <code className="font-mono bg-white/5 px-1.5 py-0.5 rounded">mofa demo</code> or <code className="font-mono bg-white/5 px-1.5 py-0.5 rounded">mofa run meeting</code> to produce deliverables.
          </p>
        </div>
      )}

      {/* Modal Preview */}
      <ArtifactPreview
        artifact={selectedArtifact}
        onClose={() => setSelectedArtifact(null)}
      />
    </motion.div>
  );
}
