//! Engine config provisioning: offline-friendly by default (local Ollama), with
//! cloud image/video lit up when `AGNES_API_KEY` is set — same binary, both modes.

use std::path::{Path, PathBuf};

/// Directory for generated artifacts, under `$CACHE/mofa-studio` so it can be named
/// once in `tauri.conf.json`'s asset-protocol scope and survives a `cargo clean`.
pub fn studio_artifacts_dir() -> Result<PathBuf, String> {
    let dir = dirs::cache_dir()
        .unwrap_or_else(std::env::temp_dir)
        .join("mofa-studio")
        .join("artifacts");
    std::fs::create_dir_all(&dir).map_err(|e| format!("creating {}: {e}", dir.display()))?;
    Ok(dir)
}

/// Write the engine config: local Ollama for chat, plus the Agnes gateway (chat +
/// image + video) when `AGNES_API_KEY` is present.
pub fn provision_config(artifacts_dir: &Path) -> Result<PathBuf, String> {
    let dir = dirs::cache_dir()
        .unwrap_or_else(std::env::temp_dir)
        .join("mofa-studio");
    std::fs::create_dir_all(&dir).map_err(|e| format!("creating {}: {e}", dir.display()))?;

    // Cloud video is a slow poll-until-done task, so widen the request/inference
    // budgets well past the defaults or a still-rendering clip gets killed mid-poll.
    let mut toml = format!(
        "# Auto-generated by mofa-studio.\n\
         [timeouts]\n\
         request_secs = 900\n\
         inference_secs = 840\n\n\
         [artifacts]\n\
         dir = {artifacts:?}\n\n\
         [[providers]]\n\
         name = \"ollama\"\n\
         kind = \"ollama\"\n\
         base_url = \"http://127.0.0.1:11434\"\n\
         priority = 2\n\
         cost_tier = \"free\"\n",
        artifacts = artifacts_dir.to_string_lossy(),
    );

    // Agnes (free OpenAI-compatible gateway): only added when a key is present, so
    // the studio stays a clean offline build otherwise.
    if let Ok(key) = std::env::var("AGNES_API_KEY")
        && !key.trim().is_empty()
    {
        let base = std::env::var("AGNES_BASE_URL")
            .unwrap_or_else(|_| "https://apihub.agnes-ai.com/v1".into());
        let chat = std::env::var("AGNES_CHAT_MODEL").unwrap_or_else(|_| "agnes-2.5-flash".into());
        let image =
            std::env::var("AGNES_IMAGE_MODEL").unwrap_or_else(|_| "agnes-image-2.1-flash".into());
        let video =
            std::env::var("AGNES_VIDEO_MODEL").unwrap_or_else(|_| "agnes-video-v2.0".into());
        // Chat + image over one openai_compatible provider.
        toml.push_str(&format!(
            "\n[[providers]]\n\
             name = \"agnes\"\n\
             kind = \"openai_compatible\"\n\
             base_url = {base:?}\n\
             api_key = \"env:AGNES_API_KEY\"\n\
             priority = 1\n\
             cost_tier = \"low\"\n\
             [[providers.models]]\n\
             name = {chat:?}\n\
             capability = \"chat\"\n\
             [[providers.models]]\n\
             name = {image:?}\n\
             capability = \"image_gen\"\n",
        ));
        // Video is a separate task-based endpoint: the cloud_video_gen backend with
        // the `agnes` dialect (submit /videos → poll → download).
        toml.push_str(&format!(
            "\n[[providers]]\n\
             name = \"agnes-video\"\n\
             kind = \"cloud_video_gen\"\n\
             dialect = \"agnes\"\n\
             base_url = {base:?}\n\
             api_key = \"env:AGNES_API_KEY\"\n\
             priority = 1\n\
             cost_tier = \"low\"\n\
             [[providers.models]]\n\
             name = {video:?}\n\
             capability = \"video_gen\"\n",
        ));
        tracing::info!("Agnes gateway configured (chat + image + video)");
    }

    let config = dir.join("config.toml");
    std::fs::write(&config, toml).map_err(|e| format!("writing {}: {e}", config.display()))?;
    Ok(config)
}
